### ISSUE TITLE
Supported game with correct checksum = Invalid Checksum

### ISSUE THREAD

**Issue by RetroGameTalk** [BttrDrgn/GCN-Translations#4]
Hello, i don't understand one thing.
Why do the supported games give invalid checksum?
If the patch was created for them, what other file is expecting?

My file:
File: Giftpia [J].iso   SHA-1: 52d0610ae78a2a5bc4bdd79cf3bfcd97c7f0a638
![2](https://user-images.githubusercontent.com/8179611/173379576-f9862897-7fb3-4c2d-91e7-01c024a0b9da.png)

Same as required file:
![1](https://user-images.githubusercontent.com/8179611/173379646-0178c55a-d46b-4a22-adc0-584f326fff07.png)

Yet it doesn't work:
![3](https://user-images.githubusercontent.com/8179611/173379708-9c28ccaa-be81-4850-b99b-691d98d6bd0c.png)

**Comment by BttrDrgn** [comment]
That is strange. This is the example patch in releases right? I personally did not test Giftpia as there are no edits to patch that aren't from the original release but HomeLand worked fine.

Since there isn't any new edits I wouldn't be discouraged from trying out future releases, sorry you are having issues patching though. I will look into it when I get home.

**Comment by RetroGameTalk** [comment]
Yes the one from releases.
If it's the same from the original creator it explains why it doesn't work. Because his doesn't work either.
I got to this fork because I ran into that problem with his patches.
I only tried Giftpia.
If Homeland works then it's safe to assume lupin has same problem as Giftpia.
If you could make a release of these xdelta fixed it would be great for me.

**Comment by BttrDrgn** [comment]
Oh okay, interesting that his don't work, I never tried them and assumed they did. Thank you for the information! I'll make a release soon with fixed patches.
